
FROM python:3.9

COPY . /app/
RUN pip install -r /app/requirements.txt

WORKDIR /app/
CMD [ "python", "-u", "api_connector.py", "--corp_id", "1282059165", "--region_id", "10000060", "--month", "8" ]